- name: Create Vaultwarden directory
  file:
    path: "{{ vaultwarden_dir }}"
    state: directory
    owner: root
    group: docker
    mode: "0755"

- name: Deploy Vaultwarden compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ vaultwarden_dir }}/docker-compose.yml"
    owner: root
    group: docker
    mode: "0644"

- name: Start Vaultwarden
  community.docker.docker_compose_v2:
    project_src: "{{ vaultwarden_dir }}"
    state: present
