- name: Create Portainer directory
  file:
    path: "{{ portainer_dir }}"
    state: directory
    owner: root
    group: docker
    mode: "0755"

- name: Deploy Portainer compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ portainer_dir }}/docker-compose.yml"
    owner: root
    group: docker
    mode: "0644"

- name: Start Portainer
  community.docker.docker_compose_v2:
    project_src: "{{ portainer_dir }}"
    state: present
